spring:
  redis:
    #host:
    #port:
    password:
    lettuce:
      pool:
        max-active: 250         # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 6000        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1ms
        max-idle: 250           # 连接池中的最大空闲连接 默认 8
        min-idle: 150           # 连接池中的最小空闲连接 默认 0
    sentinel:
      master: ems800
      nodes: 10.115.104.125:26379,10.115.104.126:26379,10.115.104.127:26379
    database: 7

server:
  port: 8088

domain:
  gomedq:
    address: 10.0.3.21,10.0.3.24
    suffix: gome.inc
    dqaddomain: http://10.128.36.111:8011/AppService.asmx?op=SetAdUserPassword
    timeout:
      read: 4000
      connect: 3000
  gomehlw:
    address: 10.144.4.81
    suffix: gis.gome.inc
    hlwaddomain: http://10.128.36.111:8011/AppService.asmx?op=SetAdUserPassword
    timeout:
      read: 4000
      connect: 3000
  gomekg:
    address: 10.129.0.6
    suffix: gomeholdings.grp
    timeout:
      read: 4000
      connect: 3000
  isExpired:
    url: http://10.128.16.54/ApiService/ADService.asmx

dubbo:
  application:
    name: auc-consumer # 消息者名字
  registry:
    address: zookeeper://10.58.22.192:2181?backup=10.58.22.193:2181,10.58.22.191:2181,10.58.166.145:2181,10.58.166.146:2181 # 注册中心地址

swagger:
  host: localhost:8080
  enabled: false

sys:
  log2his:
   day: 7

gfs:
  image:
    url: http://gfs.ds.gome.com.cn/api/fileup
    token: 1bc225b7e47e4c24bc14e4c11dfeb2d1
  file:
    url: http://gfs.ds.gome.com.cn/api/uploadFile
    token: 88dea35c41764f40b53b4ffc660335a6
  # 上传文件大小限制，单位M， 默认是20M
  upload:
    max-size: 20
